### ISSUE TITLE
Getting 404 on Get license page.

### ISSUE THREAD

**Issue by nithinkvGitHub** [extent-framework/extentreports-csharp#144]
Getting page not found for version 5 license to buy, please update as we are looking for .net version 5 licensed reporter.

**Comment by MaheshGooner** [comment]
+1 interested in upgraded/licensed .net version!

**Comment by nlnpraveen** [comment]
There is a 404 on the license page and the support page. Is anybody able to provide an answer to this?

**Comment by Brian-Watson** [comment]
I noticed the contact page is also 404 now too.  Seems like the project is dead?

@anshooarora Is ExtentReports version 5 in development still?

**Comment by joegardiner** [comment]
2 years later, still no replies and 404 on multiple pages to look at klov/v5 licenses, definitely appears abandoned.

**Comment by anshooarora** [comment]
All,

Due to personal and professional obligations, I have not had the required bandwidth to focus on open-source. I have re-started work on the Java version and will soon complete and release version 5 for .NET as well - which is currently in develop and you can view/checkout the code from https://github.com/extent-framework/extentreports-csharp/tree/develop. 

Professional release will no longer be available for purchase and some features (including some reporters) will slowly be ported over to open-source versions.

Cheers,

Anshoo
