### ISSUE TITLE
Using HTML Report, Node inside a Node in not collapsible

### ISSUE THREAD

**Issue by garry-edmonds** [extent-framework/extentreports-csharp#85]
If when using the Extent Report 4.0.3 version and HtmlReport(v4)
Create a ParentTest (Namespace)
Then inside ParentTest Create Node1 (Node_1)
Then inside Node1 create Node1.1 (Node_1_1)

When closing Node_1 I would expect not to see Node_1_1 to be shown along with any other nodes created under Node_1 this is not the case and the Node_1_1 is always shown as the Node is not created under the Dive marked as collapsed when closed.

![Extent_Node_Inside_Node](https://user-images.githubusercontent.com/7498060/75099175-8743d580-55b6-11ea-8dba-1493553b3034.png)

The screenshot is in the collapsed state.

**Comment by Overclock303** [comment]
yes i experiment the same issue and it s very annoying. 
It should be like a treeview node, all children must be hidden under the parent node.
Actually i must change my point of view by using the HtmlReport due to this limitation.

**Comment by Overclock303** [comment]
well...i changed the code of the 4.0.3 because i don't use the 4.1.0 because of dependencies revamp. i will see later on time when i ll switch to .Net 5. but anyway i changed the code  in extentreports-csharp-4.0.3 :

\extentreports-csharp-4.0.3\ExtentReports\Views\Html\Partials\RecurseNodes.cshtml

just move the code below 
@if (node.HasChildren)  {@Include("RecurseNodes", node)}

into the <div class="collapse">  juste before its </div>

now it collapse with the RecurseNodes and it works like a charm :)
Juste recompile the dll and use the fixed version. It works perfectly.

**Comment by Overclock303** [comment]
commit to 4.1.0

**Comment by anshooarora** [comment]
@garry-edmonds This is the default behavior starting version 5 (currently in alpha).  Notes from other thread:

> HtmlReporter is deprecated and replaced by SparkReporter; KlovReporter will be a separate release ([here](https://www.nuget.org/packages/klov-reporter/5.0.0-alpha5); all packages built on .NET Standard 2.0
